# Generated by Django 3.2.4 on 2021-06-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210623_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_created'], 'verbose_name': 'Review'},
        ),
    ]
